# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "xhci_pci" "usbhid" "sd_mod" "sr_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-c2b3babb-67e5-4015-8fdf-066043581309";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-c2b3babb-67e5-4015-8fdf-066043581309".device = "/dev/disk/by-uuid/c2b3babb-67e5-4015-8fdf-066043581309";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F666-1D2A";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
